var dateUtils = require("../../util/date-utils");

module.exports = {
    department: {
        name: "LAFD",
        platoons: [
            "A",
            "B",
            "C"
        ],
        schedule: {
            name: "Schedule Name",
            numberOfPlatoons: 3,
            platoonSchedule: "A,C,A,B,A,B,C,B,C",
            shiftLengthInHours: 24,
            shiftStartTime: "0800",
            platoonScheduleStartDate: dateUtils.dateFromDayMonthYear(25, 6, 2016),
            platoonColorCodes: [
                {platoon: "A", hexColor: "#ff0000"},
                {platoon: "B", hexColor: "#0000ff"},
                {platoon: "C", hexColor: "#00897B"}
            ]

        },
        ranks: [
            "A/C",
            "A/O",
            "B/C",
            "CI",
            "CII",
            "EMS",
            "DIVER",
            "EIT",
            "ENGR",
            "FF",
            "FFPM",
            "MATE",
            "MATE/P",
            "P2",
            "PIL1",
            "PIL1/P",
            "PIL2",
            "PIL2/P",
            "PIL3",
            "PIL3/P",
            "PIL4",
            "PIL4/P",
            "PIL5",
            "PIL5/P",
            "PILOT",
            "SUPR"
        ]
        /*,
        ahCodes : [
            "A01",
            "A02",
            "A03",
            "A04",
            "A05",
            "A06",
            "A07",
            "A08",
            "A09",
            "A10",
            "A11",
            "A12",
            "A13",
            "A14",
            "A15",
            "A16",
            "A17",
            "A18",
            "A19",
            "A20",
            "B01",
            "B02",
            "B03",
            "B04",
            "B05",
            "B06",
            "B07",
            "B08",
            "B09",
            "B10",
            "B11",
            "B12",
            "B13",
            "B14",
            "B15",
            "B16",
            "B17",
            "B18",
            "B19",
            "B20",
            "C01",
            "C02",
            "C03",
            "C04",
            "C05",
            "C06",
            "C07",
            "C08",
            "C09",
            "C10",
            "C11",
            "C12",
            "C13",
            "C14",
            "C15",
            "C16",
            "C17",
            "C18",
            "C19",
            "C20",
        ]
        */
    }
};
